In [5]:
import numpy as np
x = np.array(["A",50,56,89,45])
print(x)
print(type(x))
print(x.dtype)

['A' '50' '56' '89' '45']
<class 'numpy.ndarray'>
<U2


In [7]:
#create a2 array
a2 = np.array([[20,30],[30,60]])
print(a2)
print(type(x))

[[20 30]
 [30 60]]
<class 'numpy.ndarray'>


In [9]:
#Reshaping an array
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(type(b))

[[10 20]
 [30 40]]
<class 'numpy.ndarray'>


In [13]:
#create an array([1.345,3.456,4.9123])
d=np.array([1.456,35.67])
np.around(d,2)
print(np.around(np.sqrt(d),2))

[1.21 5.97]


In [16]:
#use astype() to convert the data type
a1 = np.array([[2,3,5,7,np.NAN]])
a1_copy1 = a1.astype(float)
print(a1)
print(type(a1))
a1.dtype

[[ 2.  3.  5.  7. nan]]
<class 'numpy.ndarray'>


dtype('float64')

In [18]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['2.0' '3.0' '5.0' '7.0' 'nan']]


dtype('<U32')

In [24]:
a2 =np.array([[4,6,8],[4,6,8,],[5,9,5]])
a2

array([[4, 6, 8],
       [4, 6, 8],
       [5, 9, 5]])

In [25]:
print(a2.sum(axis=1))
print(a2.sum(axis=0))

[18 18 19]
[13 21 21]


In [27]:
#find the mean along with rows and columns
print(np.mean(a2,axis=1))
print(np.mean(a2,axis=0))

[6.         6.         6.33333333]
[4.33333333 7.         7.        ]


In [29]:
#matrix opeartions
a3 = np.array([[3,4,5],[4,5,6],[8,7,8]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[3 4 5]
 [4 5 6]
 [8 7 8]]
[[0 4 5]
 [4 0 6]
 [8 7 0]]


In [31]:
#Define two matrices
A = np.array([[1,2], [3,4]])
B = np.array([[5,6],[4,5]])
c = np.matmul(A,B)
print(c)

[[13 16]
 [31 38]]


In [32]:
#print the transpose of the matrix
print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 4]
 [6 5]]


In [33]:
a4 = np.array([[3,4,5],[4,7,8],[5,8,5]])
a4

array([[3, 4, 5],
       [4, 7, 8],
       [5, 8, 5]])

In [34]:
a4[0::3,0::2]

array([[3, 5]])

In [38]:
#slicing of an array
a4[1:3,0:2]

array([[4, 7],
       [5, 8]])